apiVersion: v1
kind: Service
metadata:
  name: wp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wp
  ports:
    - name: wp
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  selector:
    matchLabels:
      app: wp
  replicas: 1
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wp_img
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wp
