apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: main
      protocol: TCP
      port: 21
      targetPort: 21
    - name: data
      protocol: TCP
      port: 20
      targetPort: 20
    - name: pasv
      protocol: TCP
      port: 49001
      targetPort: 49001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: main
        - containerPort: 20
          name: data
        - containerPort: 49001
          name: pasv
        volumeMounts:
        - name: ftps-storage
          mountPath: /var/www
      volumes:
      - name: ftps-storage
        persistentVolumeClaim:
          claimName: ftps-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000M
